sudo: required
language: generic
env:
#- TARGET_CPU=x64 TYPE=Debug VERSION=67
- TARGET_CPU=x64 TYPE=Release VERSION=68
- TARGET_CPU=arm64 TYPE=Release VERSION=68
services:
- docker
script:
- docker build -t builder .
- mkdir output
- docker run --volume $(pwd)/output:/output --env TARGET_CPU=${TARGET_CPU} --env TYPE=${TYPE} --env VERSION=${VERSION} --env BUILD=$(git describe) --env OUTPUT=/output builder
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: cr3kF3+BxMNEGpPt9q+Ws2r677YsLfWLLTWO2Z+VfY5HW9smIYdYs9FinNCHgybCWS6KSaFZwcJE5K/m2qXiEHgX+k642GcepviH540u0e8qbjHNGiKMfjIKnQfgQLEQ/lWze8zJ6ihQJ9yMx5MRP0B8YhsGrs5rX2nKJclAzI3wGG8rOyP5N4MIGAx5e/nhr6co5ikTeskU8DAWMSoA/1IQQWInFOmnQEggM0hxhjnr7gY/ka1J3wwZr6zDm8sNMopU62wpSl6AffQaaJxO6ex2ocCaIrNxuD7eqzI3zaTZPBKcNcMRv4M8db+qZl0SSYVfH25cjpBxYDVIhoBoGs07nhYjSwxhjz+Qq38fepJbQ9C0qS27Kdks7LMTi1tLDAmQwwUsnqTvX5RPUdBZ+ZcadmlseUTdonZLvc2XE3QHfBGYHBsK/S0+xxFjC7dUj5091YRsTlaK2C0yExAPoRAxGmf50ypzoX+vZK1GU1VsqG6GLMFs9XB2jQ7VzyUSu8RTcXrElTIqQcuCOOgrSpJHczL4EWdq76ePcYZBHaX76P+M8mwLP3+WFJQZUdfzS+adTmndwpUwrQ1KaJ2Km4l85gS+YZCSsn21vMOlQZ4EFf/ee7yjnebeOCIlIUzzo8RwszQ+6bikRAPVfjYOTygEYfJsYJLoDi3j9KXJIBY=
  file_glob: true
  file: "output/*.deb"
  on:
    tags: true
    repo: otamachan/webrtc-build
