on: push
name: Build
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x64
          - arm64
          - arm
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create deb package
      env:
        TARGET_CPU: ${{ matrix.target }}
        VERSION: 4147
        TYPE: Release
      run: |
        docker build -t builder .
        mkdir output
        docker run --volume $(pwd)/output:/output --env TARGET_CPU=${TARGET_CPU} --env TYPE=${TYPE} --env VERSION=${VERSION} --env BUILD=$(git describe) --env OUTPUT=/output builder
